#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  main.py
#  
#  Copyright 2013 Ambergleam <ambergleam@gmail.com>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  

# The problem we're working on
problem = "2"

# Problem description
description = """
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

# Sum of all the terms
solution = 0

# Solve the problem
def solve(first=1, second=1):
	global solution
	third = first + second
	if (third < 4000000):
		if (third % 2 == 0):
			print third
			solution += third
		return solve(second, third)
	return solution	

# Main function that just runs the solver
def main():
	print "Problem " + problem
	print description
	print "...\n"
	solve()
	print "\n...\n"
	print solution
	return 0

# The actual main function for command line run
if __name__ == '__main__':
	main()
